# Generated by Django 3.0.3 on 2020-02-18 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0004_auto_20200218_0629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='desc',
            new_name='stuffs',
        ),
    ]
