# Generated by Django 3.0.3 on 2020-02-18 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0005_auto_20200218_0630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
